In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import namedtuple
import json, os
import scipy.optimize
import ase
from ase.build import molecule
from ase.optimize import BFGS
from ase import Atoms
from ase.data.pubchem import pubchem_atoms_search, pubchem_atoms_conformer_search
#from gpaw import GPAW, PW
from ase.calculators.emt import EMT
from ase.io import write

plt.rc('font', size=16) # set font size in plots to 12

In [13]:
# Input name or SMILES of compound

#no_salt = int(input('No of salts: '))
no_solvent = int(input('No of solvent: '))

print('Input method: name')

solvents = []
for c in range(no_solvent):
    solvent_input =input(f'Write name of solvent {c+1}: ')
    solvent_URL = solvent_input.replace(' ', '%20')
    solvents.append(solvent_URL)

#salts = []
#for c in range(no_salt):
#    salt_input = input(f'Write name of salt {c+1}: ')
#    salt_URL = salt_input.replace(' ', '%20')
#    salts.append(salt_URL)


for c in range(len(solvents)):
    solvent = pubchem_atoms_search(name=solvents[c])
    #print(solvent)
    print(solvent.positions)
    print(solvent.symbols)

    calc = EMT()
    solvent.calc = calc
    opt = BFGS(solvent, logfile='opt.log')
    opt.run(fmax=0.05)
    print(solvent.positions)
    print(solvent.symbols)

No of solvent:  1


Input method: name


Write name of solvent 1:  propylene carbonate


Atoms(symbols='O3C4H6', pbc=False, initial_charges=...)
[[-2.1800e-02  9.5080e-01  4.0500e-02]
 [ 7.8400e-01 -1.1505e+00  3.3300e-02]
 [ 2.2453e+00  6.1540e-01 -9.5100e-02]
 [-1.0961e+00  8.6500e-02  3.9260e-01]
 [-6.2570e-01 -1.2401e+00 -1.2620e-01]
 [-2.3928e+00  5.5920e-01 -2.3170e-01]
 [ 1.1072e+00  1.7870e-01 -1.3400e-02]
 [-1.1805e+00  8.4100e-02  1.4860e+00]
 [-1.0253e+00 -2.0793e+00  4.5010e-01]
 [-8.4320e-01 -1.3980e+00 -1.1881e+00]
 [-2.2992e+00  6.4710e-01 -1.3198e+00]
 [-3.2155e+00 -1.2440e-01 -2.5000e-03]
 [-2.6511e+00  1.5567e+00  1.3970e-01]]
O3C4H6
[8 8 8 6 6 6 6 1 1 1 1 1 1]
[[-0.46336377  0.60453521 -0.92069347]
 [ 0.07124528 -0.9543592  -0.59579635]
 [ 1.1198743  -0.19435141  0.23781816]
 [-1.19066602 -0.41440897 -0.12625987]
 [-0.18641356 -0.44664577  0.8430782 ]
 [-0.99661528  0.73000841  0.57806274]
 [ 0.26290956  0.88770023  0.34151412]
 [-1.4855105  -0.21584933  1.5743502 ]
 [-0.99571729 -1.75555934  0.28858802]
 [-0.99188661 -0.63612728 -1.65924191]
 [-2.115354